// Turns lib/content/defaults.ts into supabase/seed.sql.
// Usage: npm run seed:sql -- you@email.com   (the email becomes the first admin)
import { writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";

const json = execFileSync(process.execPath, [
  "--experimental-strip-types", "--no-warnings", "--input-type=module", "-e",
  `import { DEFAULT_SETTINGS, DEFAULT_CONTENT } from "./lib/content/defaults.ts"; console.log(JSON.stringify({ s: DEFAULT_SETTINGS, c: DEFAULT_CONTENT }))`,
], { encoding: "utf8" });
const { s, c } = JSON.parse(json);
const admin = process.argv[2] || "acegraphiix@gmail.com";

const q = (v) => (v === null || v === undefined ? "null" : `'${String(v).replace(/'/g, "''")}'`);
const arr = (a) => `array[${a.map(q).join(",")}]::text[]`;
const b = (v) => (v ? "true" : "false");

const out = [];
out.push(`-- Generated by scripts/make-seed.mjs from lib/content/defaults.ts. Run AFTER schema.sql, once.`);
out.push(`insert into admins (email) values (${q(admin)}) on conflict do nothing;`);
out.push(`insert into settings (id, data) values (1, ${q(JSON.stringify(s))}::jsonb) on conflict (id) do nothing;`);
for (const r of c.services)
  out.push(`insert into services (title, description, features, price, unit, icon, published, position) values (${q(r.title)}, ${q(r.description)}, ${arr(r.features)}, ${q(r.price)}, ${q(r.unit)}, ${q(r.icon)}, ${b(r.published)}, ${r.position});`);
for (const r of c.steps)
  out.push(`insert into process_steps (title, tags, icon, position) values (${q(r.title)}, ${arr(r.tags)}, ${q(r.icon)}, ${r.position});`);
for (const r of c.experience)
  out.push(`insert into experience (role, company, period, bullets, position) values (${q(r.role)}, ${q(r.company)}, ${q(r.period)}, ${arr(r.bullets)}, ${r.position});`);
for (const r of c.testimonials)
  out.push(`insert into testimonials (name, role, quote, tags, rating, photo_url, published, position) values (${q(r.name)}, ${q(r.role)}, ${q(r.quote)}, ${arr(r.tags)}, ${r.rating}, ${q(r.photo_url)}, false, ${r.position});`);
for (const r of c.tools)
  out.push(`insert into tools (name, description, percent, icon, position) values (${q(r.name)}, ${q(r.description)}, ${r.percent}, ${q(r.icon)}, ${r.position});`);
for (const r of c.faqs)
  out.push(`insert into faqs (question, answer, published, position) values (${q(r.question)}, ${q(r.answer)}, ${b(r.published)}, ${r.position});`);

writeFileSync("supabase/seed.sql", out.join("\n") + "\n");
console.log(`supabase/seed.sql written (admin: ${admin})`);
